name: sweep_blocksworld_it3
program: ./train_network.py
method: bayes
metric: 
  name: val_loss
  goal: minimize
parameters:
  iteration:
    distribution: constant
    value: 3
  learning_rate: 
    distribution: categorical
    values: [0.01, 0.001, 0.0001]
  lstm_units:
    distribution: int_uniform
    min: 100
    max: 500
  embedding_dim:
    distribution: int_uniform
    min: 50
    max: 400
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  rec_dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  l1:
    distribution: categorical
    values: [0.0, 0.1]
  l2:
    distribution: categorical
    values: [0.0, 0.1]
  epochs:
    distribution: constant
    value: 30
  batch_size:
    distribution: categorical
    values: [32, 64]
  max_plan_dim:
    distribution: constant
    value: 75
  project_name:
    distribution: constant
    value: fast_and_slow_goal_plan_recognition
  domain: 
    distribution: constant
    value: blocksworld
  min_plan_perc:
    distribution: constant
    value: 0.3
  max_plan_perc:
    distribution: constant
    value: 1.0
  augmentation_plans:
    distribution: categorical
    values: [1,3]
  use_full_plan:
    distribution: constant
    value: True
  patience:
    distribution: constant
    value: 10
  